<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA2uyl0e\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA2uyl0e/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA2uyl0e.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA2uyl0e\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA2uyl0e\App_KernelDevDebugContainer([
    'container.build_hash' => 'A2uyl0e',
    'container.build_id' => '5a80f5c4',
    'container.build_time' => 1610033160,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA2uyl0e');
